language: cpp
sudo: false
matrix:
  allow_failures:
    - compiler: clang
      env:
        - CXX_COMPILER='clang++-3.9'
        - C_COMPILER='clang-3.9'
        - Fortran_COMPILER='gfortran'
        - BUILD_TYPE='release'
        - NAME='clang'
        - VERSION='3.9'

  include:

  - os: linux
    compiler: clang
    addons: &1
      apt:
        sources:
        - llvm-toolchain-precise-3.6
        - ubuntu-toolchain-r-test
        - george-edison55-precise-backports
        packages:
        - python-numpy
        - cmake
        - cmake-data
        - liblapack-dev
        - clang-3.6
        - libhdf5-serial-dev
        - gfortran
    env:
      - CXX_COMPILER='clang++-3.6'
      - C_COMPILER='clang-3.6'
      - Fortran_COMPILER='gfortran'
      - BUILD_TYPE='release'
      - NAME='clang'
      - VERSION='3.6'

  - os: linux
    compiler: clang
    addons: &2
      apt:
        sources:
        - llvm-toolchain-precise-3.9
        - ubuntu-toolchain-r-test
        - george-edison55-precise-backports
        packages:
        - python-numpy
        - cmake
        - cmake-data
        - liblapack-dev
        - clang-3.9
        - libhdf5-serial-dev
        - gfortran
    env:
      - CXX_COMPILER='clang++-3.9'
      - C_COMPILER='clang-3.9'
      - Fortran_COMPILER='gfortran'
      - BUILD_TYPE='release'
      - NAME='clang'
      - VERSION='3.9'


#  - os: linux
#    compiler: gcc
#    addons: &3
#      apt:
#        sources:
#        - ubuntu-toolchain-r-test
#        - george-edison55-precise-backports
#        packages:
#        - python-numpy
#        - cmake
#        - cmake-data
#        - liblapack-dev
#        - libhdf5-serial-dev
#        - g++-4.9
#        - gcc-4.9
#        - gfortran-4.9
#    env:
#      - CXX_COMPILER='g++-4.9'
#      - C_COMPILER='gcc-4.9'
#      - Fortran_COMPILER='gfortran-4.9'
#      - BUILD_TYPE='release'
#      - NAME='gcc'
#      - VERSION='4.9'
#
#  - os: linux
#    compiler: gcc
#    addons: &4
#      apt:
#        sources:
#        - ubuntu-toolchain-r-test
#        - george-edison55-precise-backports
#        packages:
#        - python-numpy
#        - cmake
#        - cmake-data
#        - libhdf5-serial-dev
#        - liblapack-dev
#        - g++-6
#        - gcc-6
#        - gfortran-6
#    env:
#      - CXX_COMPILER='g++-6'
#      - C_COMPILER='gcc-6'
#      - Fortran_COMPILER='gfortran-6'
#      - BUILD_TYPE='release'
#      - NAME='gcc'
#      - VERSION=6
#  - os: linux
#    compiler: gcc
#    addons: *4
#    env:
#      - CXX_COMPILER='g++-6'
#      - C_COMPILER='gcc-6'
#      - Fortran_COMPILER='gfortran-6'
#      - BUILD_TYPE='debug'
#      - NAME='gcc'
#      - VERSION=6


before_install:
  - uname -a
  - free -m
  - df -h
  - ulimit -a
  - python -V
install:
- DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
- mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}
- |
  if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
    brew install cmake python
  fi
before_script:
- python -c 'import numpy; print numpy.version.version'
- cd ${TRAVIS_BUILD_DIR}
- export CXX=${CXX_COMPILER}
- export CC=${C_COMPILER}
- export FC=${Fortran_COMPILER}
- export CTEST_OUTPUT_ON_FAILURE=1
- ${CXX_COMPILER} --version
- ${Fortran_COMPILER} --version
- ${C_COMPILER} --version
- mkdir ${TRAVIS_BUILD_DIR}/libint
- wget http://vergil.chemistry.gatech.edu/test_sphinxman/libint_x86_64.tgz
- tar -xzvf libint_x86_64.tgz -C ${TRAVIS_BUILD_DIR}/libint
- > 
    cmake -Bbuild -H. 
    -DCMAKE_CXX_COMPILER=${CXX_COMPILER} 
    -DCMAKE_C_COMPILER=${C_COMPILER} 
    -DCMAKE_BUILD_TYPE=${BUILD_TYPE} 
    -DCMAKE_PREFIX_PATH=${TRAVIS_BUILD_DIR}/libint
    -DENABLE_CHEMPS2=off 
    -DCMAKE_INSTALL_PREFIX=${TRAVIS_BUILD_DIR}/Install
- cd build
- ../.scripts/travis_build.sh
script:
- python ../.scripts/travis_run_test.py
- python ../.scripts/travis_print_failing.py
